// CBho.idl : IDL source for CBho
//

// This file will be processed by the MIDL tool to
// produce the type library (CBho.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(0B9CA036-554B-474E-B920-74035F37B369),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IPageCapture : IDispatch{
};
[
	object,
	uuid(B051BE98-C45B-46AB-8A2A-CFFD939CDA74),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IProxySwitch : IDispatch{
};
[
	uuid(89711670-D382-4BFF-9BF6-F84407E8541A),
	version(1.0),
]
library CBhoLib
{
	importlib("stdole2.tlb");
	[
		uuid(7EEF1B3C-280A-4C17-A1F0-45AD0CFDAECE)		
	]
	coclass PageCapture
	{
		[default] interface IPageCapture;
	};
	[
		uuid(B2611A8C-379A-4AC6-8412-B8CAF5C42ED0)		
	]
	coclass ProxySwitch
	{
		[default] interface IProxySwitch;
	};
};

